# 工程配置 ==> 默认的服务名
spring:
   application:
      name: sc-server
      
server:
   port: 8000

eureka:
   client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
         # 注册侧服务器的地址
         defaultZone: http://127.0.0.1:8100/eureka,http://127.0.0.1:8200/eureka
         
---
spring:
   profiles: cs1
server:
   port: 8100
eureka:
   client:
      serviceUrl:
         defaultZone: http;//127.0.0.1:8000/eureka,http://127.0.0.1:8200/eureka  

---
spring:
   profiles: cs2
server:
   port: 8200
eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:8100/eureka,http://127.0.0.1:8000/eureka                  
        
